name: Build and Push Docker Image to DockerHub

on:
  push:
    branches:
      - main  # Triggers on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Triggers on pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to DockerHub using the secrets
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/vastai_ai_cad_point2cyl:latest .

      # Step 4: Push the Docker image to DockerHub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/vastai_ai_cad_point2cyl:latest

      # Step 5: Log out from DockerHub
      - name: Log out from DockerHub
        run: docker logout
